name: crud_flutter_app
description: A Flutter CRUD app example

version: 1.0.0+1

# Add SDK version constraints in the environment section
environment:
  sdk: ">=3.7.0 <4.0.0"  # Adjust according to your installed Dart SDK version

dependencies:
  flutter:
    sdk: flutter

  http: 1.4.0
  provider: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets: []
